import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {},
  containerScroll: {
    backgroundColor: "#0036AE",
    width: "100%",
  },
  containerMain: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    width: "100%",
    height: "100%",
  },
  containerCard: {
    backgroundColor: "#ffffff",
    top: 20,
    marginLeft: 35,
    marginBottom: 30,
    flexDirection: "row",
    width: "80%",
    height: 190,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "flex-start",
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  card: {
    width: "100%",
    height: "100%",
    flexDirection: "row",
    top: 2,
  },
  containerDataCard: {
    top: -80,
    marginLeft: 45,
    width: "90%",
    marginBottom: -30,
  },
  numberCard: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#e3e4e5",
    letterSpacing: 4,
  },
  nameCard: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#e3e4e5",
  },
  expiredCard: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#e3e4e5",
    textAlign: "center",
  },
  containerInfoCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginLeft: "5%",
    width: "90%",
    height: 200,
    justifyContent: "flex-start",
  },
  input: {
    backgroundColor: "#EEF1F8",
    color: "black",
    width: "100%",
    height: 40,
    marginTop: 10,
    borderRadius: 10,
    paddingLeft: 10,
  },
  inputCvv: {
    backgroundColor: "#EEF1F8",
    color: "black",
    width: "100%",
    height: 40,
    marginTop: 10,
    borderRadius: 10,
    paddingLeft: 10,
    marginLeft: 15,
  },
  titleInfoCard: {
    fontWeight: "bold",
    color: "#8A8A8A",
  },
  expiredInfoCard: {
    fontWeight: "bold",
    color: "#8A8A8A",
    marginLeft: 110,
  },
  spinnerTextStyle: {
    color: "#FFFFFF",
  },
});
export default styles;
