import { StyleSheet, Dimensions } from "react-native";
import { ProductCard } from "../../AppStyles";
import { ProductCardSm } from "../../AppStylesSm";
const { width: viewportWidth } = Dimensions.get("window");

const styles = StyleSheet.create({
  detailSection: ProductCard.detailSection,
  operatingBox: ProductCard.operatingBox,
  reduce: ProductCard.reduce,
  btn1: ProductCard.btn1,
  inputBox: ProductCard.inputBox,
  inputValue: ProductCard.inputValue,
  plus: ProductCard.plus,
  priceDiscountSm: ProductCardSm.priceDiscount,
  containerSm: ProductCardSm.container,
  photoSm: ProductCardSm.photo,
  titleSm: ProductCardSm.title,
  priceSm: ProductCardSm.price,
  brandSm: ProductCardSm.brand,
  listProductsHorizontal: ProductCardSm.listProductsHorizontalProduct,
  containerBrandSm: ProductCardSm.containerBrand,
  containerShopSm: ProductCardSm.containerShop,
  containerShopCartItemSm: ProductCardSm.containerShopCartItem,
  containerShopFavoriteItemSm: ProductCardSm.containerShopFavoriteItem,
  containerBrandNameSm: ProductCardSm.containerBrandName,
  containerDiscountSm: ProductCardSm.containerDiscount,
  percentDiscountSm: ProductCardSm.percentDiscount,
  container: {
    backgroundColor: "white",
    flex: 1,
  },
  carouselContainer: {
    minHeight: 250,
  },
  carousel: {},

  image: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: 200,
  },
  imageContainer: {
    flex: 1,
    justifyContent: "center",
    width: viewportWidth,
    height: 200,
  },
  paginationContainer: {
    flex: 1,
    position: "absolute",
    alignSelf: "center",
    paddingVertical: 8,
    marginTop: 200,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 0,
  },
  infoProductContainer: {
    flex: 1,
    margin: 5,
    marginTop: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  infoProductContainerMain: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0036AE",
    width: "100%",
    height: 60,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  infoContainer: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#ffffff",
    width: "100%",
    height: 30,
  },
  infoContainerDetail: {
    flex: 1,
    flexDirection: "row",
    width: "90%",
    top: 2,
    alignItems: "center",
    justifyContent: "flex-start",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 3,
    shadowOpacity: 1.0,
    elevation: 3,
    marginBottom: 10,
  },
  infoContainerPrice: {
    flex: 1,
    flexDirection: "row",
    width: "90%",
    top: 2,
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 15,
  },
  detail: {
    width: "31.6%",
    height: 50,
    backgroundColor: "#ffffff",
    borderRadius: 10,
  },
  detailCenter: {
    width: "31%",
    height: 50,
    backgroundColor: "#ffffff",
  },
  detailPrice: {
    width: "80%",
    height: 50,
    backgroundColor: "#ffffff",
    borderRadius: 10,
  },
  detailBrand: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "flex-start",
    width: "20%",
    height: 50,
    backgroundColor: "#ffffff",
    borderRadius: 10,
  },
  detailSection: {
    width: "43%",
    height: 50,
    backgroundColor: "#ffffff",
    borderRadius: 10,
  },
  detailSectionFavorites: {
    width: "10%",
    height: 50,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    left: 4,
  },
  headerDetail: {
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
    color: "#0036AE",

    marginTop: 5,
  },
  infoDetail: {
    fontSize: 14,
    fontWeight: "light",
    textAlign: "center",
    color: "#FF7F50",
    marginTop: 5,
  },
  buttonContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  infoPhoto: {
    height: 20,
    width: 20,
    marginRight: 0,
  },
  infoProduct: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#0036AE",
  },
  category: {
    fontSize: 14,
    fontWeight: "bold",
    margin: 10,
    color: "#2cd18a",
  },
  infoDescriptionProduct: {
    textAlign: "left",
    fontSize: 16,
    marginTop: 30,
    margin: 15,
  },
  infoProductName: {
    fontSize: 12,
    margin: 10,

    fontWeight: "bold",
    color: "#ffffff",
    textAlign: "center",
  },
  infoProductPriceDiscount: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#FF7F50",
    marginTop: 5,
  },
  infoProductPrice: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 5,
    color: "#cccccc",

    textDecorationLine: "line-through",
    textDecorationStyle: "solid",
  },
  infoProductMsg: {
    fontSize: 15,
    fontWeight: "light",
    color: "#FF7F50",
  },
  containerCollapse: {
    flex: 1,
    width: "90%",

    borderRadius: 10,
    backgroundColor: "#ffffff",
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 3,
    shadowOpacity: 1.0,
    elevation: 3,
    marginBottom: 10,
  },
  wrapDropDownHeader: {
    paddingHorizontal: 15,
    paddingTop: 40,
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  moreInfoText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#0036AE",
    textAlign: "center",
    marginTop: -15,
    marginBottom: 10,
  },
  dropIcon: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#0036AE",
    textAlign: "center",
    marginTop: -15,
  },
  wrapDropContent: { marginHorizontal: 15, backgroundColor: "#ffffff" },
});

export default styles;
