import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  containerScroll: {
    margin: 10,
  },
  containerItemData: {
    width: "95%",
    height: 100,
    top: -40,
    marginLeft: "2.5%",
    marginBottom: 5,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  containerItem: {
    width: "95%",
    height: "auto",
    top: -30,
    marginLeft: "2%",
    marginBottom: 10,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  containerItemProducts: {
    width: "95%",
    height: 350,
    top: -30,
    marginLeft: "2%",
    marginBottom: 10,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  iconArrowForward: {
    top: 5,
  },
  map: {
    width: "100%",
    height: 200,
    top: 10,
    borderRadius: 10,
  },
  textThanks: {
    fontWeight: "bold",
    fontSize: 15,
    marginLeft: 10,
    color: "#333333",
  },
  containerStars: {
    width: "95%",
    height: 50,
    marginLeft: "2%",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
  },
  buyImageContainer: {
    flexDirection: "row",

    marginLeft: -20,
    width: "70%",
    height: 45,
    borderRadius: 10,
    top: 5,

    marginBottom: 10,
    marginLeft: 5,
  },

  titleBuy: {
    fontWeight: "bold",
    fontSize: 19,
    color: "#333333",
  },
  titleDirection: {
    fontWeight: "ligth",
    fontSize: 10,
    color: "#606060",
    marginLeft: 10,
  },
  titleProduct: {
    fontWeight: "bold",
    fontSize: 10,
    color: "#606060",
    marginLeft: 10,
    top: 10,
  },
  titleQuantity: {
    fontWeight: "ligth",
    fontSize: 10,
    color: "#606060",

    top: 10,
    textAlign: "center",
  },
  titlePayment: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 12,
    marginLeft: 5,
    top: 2,
  },
  textDetail: {
    fontWeight: "bold",
    fontSize: 15,
    color: "#FF7F50",
    marginLeft: 10,
  },

  textStatus: {
    fontWeight: "bold",
    fontSize: 20,
    color: "#FF7F50",
  },
  textDate: {
    fontWeight: "light",
    fontSize: 12,
    color: "#BCBCBC",
  },
  textDatePurchase: {
    fontWeight: "light",
    fontSize: 12,
    color: "#BCBCBC",
    marginLeft: 10,
    top: 12,
  },
  textAmount: {
    fontWeight: "bold",
    fontSize: 22,
    color: "#FF7F50",
  },
  textTotalProduct: {
    fontWeight: "bold",
    fontSize: 12,
    color: "#FF7F50",
    top: 10,
    textAlign: "left",
  },
  containerStatus: {
    flexDirection: "row",
    width: "100%",
    height: 30,
    top: 3,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  containerInfo: {
    width: "95%",
    height: 110,
    marginLeft: "2%",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
  },
  containerProduct: {
    width: "95%",
    height: 50,
    marginLeft: "2%",

    marginBottom: 10,
    flexDirection: "row",
  },
  containerDetail: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "95%",
    height: 50,
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  containerProducts: {
    top: 10,

    height: 125,
  },
  containerDetailInfo: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "95%",
    height: 40,
    top: 5,
    alignItems: "center",
    backgroundColor: "#EEEEEE",
    borderRadius: 10,
  },
  containerDetailInfoProducts: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "95%",
    height: 140,
    top: 5,
    backgroundColor: "#EEEEEE",
    borderRadius: 10,
    marginBottom: 10,
  },
  pillPayment: {
    width: 70,
    height: 20,
    borderRadius: 5,
    backgroundColor: "#FF7F50",
  },
  containerDate: {
    flexDirection: "row",
    width: "90%",
    height: 15,
    marginLeft: "5%",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
    top: -10,
  },
  /***ESTILOS MODAL */
  bottomModalView: {
    justifyContent: "flex-end",
    margin: 0,
  },
  modalTracking: {
    width: "100%",
    height: "80%",
    borderRadius: 20,
    borderWidth: 0,
    borderStyle: "solid",
    backgroundColor: "#f2f2f2",
  },
  titleModalTracking: {
    textAlign: "center",
    top: -30,
    fontSize: 18,
    color: "#333333",
    fontWeight: "bold",
  },
  containerTextTracking: {
    width: "90%",
  },
  iconCloseModal: {
    margin: 10,
  },
  containerTrackings: {
    width: "93%",
    backgroundColor: "#ffffff",
    height: "85%",
    top: 5,
    borderRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 3,
    shadowOpacity: 1.0,
    elevation: 3,
    marginBottom: 10,
    marginLeft: 10,
  },
  containerTrackingSecond: {
    marginBottom: 10,
    marginLeft: 15,
    marginTop: 15,
    flex: 1,
    flexDirection: "row",
    width: "90%",
    height: 50,
  },
  containerTextTracking: {
    width: "90%",
    marginLeft: 10,
  },
  nameTracking: {
    fontSize: "16",
    fontWeight: "bold",
    color: "#7E7E7E",
  },
  timeTracking: {
    fontSize: "13",
    fontWeight: "lighter",
    color: "#C5C5C5",
  },
  checkbox: { top: 15 },
  lineSeparator: {
    borderBottomWidth: 2,
    borderBottomColor: "#dddddd",
    width: "10%",
    top: -15,
    transform: [{ rotate: "90deg" }],
    left: 8,
  },
});
export default styles;
