import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  containerScroll: {
    margin: 10,
  },
  containerItem: {
    width: "100%",
    height: 150,
    top: 2,
    marginBottom: 10,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  buyImageContainer: {
    flexDirection: "row",

    marginLeft: -20,
    width: "70%",
    height: 45,
    borderRadius: 10,
    top: 5,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 0.8,
    elevation: 0.5,
    marginBottom: 10,
    marginLeft: 5,
  },
  titleBuy: {
    fontWeight: "bold",
    fontSize: 19,
    color: "#333333",
  },
  titleProduct: {
    fontWeight: "ligth",
    fontSize: 10,
    color: "#606060",
    marginLeft: 10,
  },
  titlePayment: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 12,
    marginLeft: 5,
    top: 2,
  },
  textStatus: {
    fontWeight: "bold",
    fontSize: 14,
    color: "#FF7F50",
  },
  textDate: {
    fontWeight: "light",
    fontSize: 12,
    color: "#BCBCBC",
  },
  textAmount: {
    fontWeight: "bold",
    fontSize: 22,
    color: "#FF7F50",
  },
  containerStatus: {
    flexDirection: "row",
    width: "90%",
    height: 25,
    marginLeft: "5%",
    top: 3,
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
  },
  containerInfo: {
    width: "95%",
    height: 110,
    marginLeft: "2%",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
  },
  containerDetail: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "95%",
    height: 50,
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  containerDetailInfo: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "95%",
    height: 40,
    top: 5,
    alignItems: "center",
    backgroundColor: "#EEEEEE",
    borderRadius: 10,
  },
  pillPayment: {
    width: 70,
    height: 20,
    borderRadius: 5,
    backgroundColor: "#FF7F50",
  },
  containerDate: {
    flexDirection: "row",
    width: "90%",
    height: 15,
    marginLeft: "5%",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
    top: -10,
  },
});
export default styles;
