import { StyleSheet } from "react-native";
import { ProductCard } from "../../AppStyles";
import { ProductCardSm } from "../../AppStylesSm";
const styles = StyleSheet.create({
  container: ProductCard.container,
  photo: ProductCard.photo,
  title: ProductCard.title,
  price: ProductCard.price,
  priceDiscount: ProductCard.priceDiscount,
  listProductsVertical: ProductCard.listProductsVertical,
  containerBrand: ProductCard.containerBrand,
  containerShop: ProductCard.containerShop,
  containerShopCartItem: ProductCard.containerShopCartItem,
  containerShopFavoriteItem: ProductCard.containerShopFavoriteItem,
  containerBrandName: ProductCard.containerBrandName,
  containerDiscount: ProductCard.containerDiscount,
  percentDiscount: ProductCard.percentDiscount,
  listBrandsHorizontalProducts: ProductCardSm.listBrandsHorizontalProducts,
  containerCategory: ProductCardSm.containerCategorySm,
  photoCategory: ProductCardSm.photoCategorySm,
  containerScroll: {
    backgroundColor: "#0036AE",
    width: "100%",
    height: "100%",
  },
  containerMain: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    width: "100%",
    height: "100%",
  },
  /*
  containerImage: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "right",
    alignItems: "right",
    height: 150,
    borderRadius: 20,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  */
  containerImage: {
    width: "100%",
    alignItems: "flex-start",
    height: 120,
  },
  photoBrand: {
    width: "100%",
    height: 150,
    borderRadius: 20,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  containerBrands: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 0,
    top: 0,
    height: "100%",
    flex: 1,
  },
  containerFilterOrder: {
    marginBottom: 10,
    marginLeft: 15,
    marginTop: 15,
    flex: 1,
    flexDirection: "row",
    width: "90%",
    height: 20,
  },
  nameFilterOrder: {
    fontSize: "16",
    fontWeight: "bold",
    color: "#FF7F50",
  },

  containerTextFilterOrder: {
    width: "90%",
  },
  lineSeparator: {
    borderBottomWidth: 1,
    borderBottomColor: "#dddddd",
    width: "90%",
    left: 15,
  },
  bottomModalView: {
    justifyContent: "flex-end",
    margin: 0,
  },
  modalFilterOrder: {
    width: "100%",
    height: "40%",
    borderRadius: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 0,
    borderStyle: "solid",
    backgroundColor: "#f2f2f2",
  },
  iconCloseModal: {
    margin: 10,
  },
  titleModalFilterOrder: {
    textAlign: "center",
    top: -30,
    fontSize: 18,
    color: "#333333",
    fontWeight: "bold",
  },
  containerFiltersOrder: {
    width: "93%",
    backgroundColor: "#ffffff",
    height: "85%",
    top: 10,
    borderRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 3,
    shadowOpacity: 1.0,
    elevation: 3,
    marginBottom: 10,
    marginLeft: 10,
  },
  containerFilter1: {
    width: "15%",
    height: 40,
    backgroundColor: "#ECECEC",
    margin: 5,
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  containerFilter2: {
    width: "35%",
    height: 40,
    backgroundColor: "#ECECEC",
    margin: 5,
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  containerFilter3: {
    width: "40%",
    height: 40,
    backgroundColor: "#ECECEC",
    margin: 5,
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  containerFilterActive3: {
    width: "40%",
    height: 40,
    backgroundColor: "#FF7F50",
    margin: 5,
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
});

export default styles;
