import { StyleSheet } from "react-native";
import { ProductCardSm } from "../../AppStylesSm";
const styles = StyleSheet.create({
  operatingBox: ProductCardSm.operatingBox,
  reduce: ProductCardSm.reduce,
  btn1: ProductCardSm.btn1,
  inputBox: ProductCardSm.inputBox,
  inputValue: ProductCardSm.inputValue,
  plus: ProductCardSm.plus,
  cartLine: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 80,
    top: 2,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  containerItemsCheckout: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 100,
    top: 2,
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  containerItemsCheckoutMethod: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 60,
    top: 2,
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
  },
  containerNewCard: {
    flexDirection: "row",
    width: "93%",
    height: 80,
    top: 2,
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "flex-start",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
    marginLeft: 10,
  },
  titleNewCard: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333333",
  },
  subtitleNewCard: {
    fontSize: 12,
    fontWeight: "light",
    color: "#cccccc",
  },
  containerFormsPay: {
    flex: 1,
    flexDirection: "row",
    width: "93%",
    height: 100,
    top: 2,
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "flex-start",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#cccccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1,
    shadowOpacity: 1.0,
    elevation: 0.5,
    marginLeft: 10,
  },
  itemsList: {
    backgroundColor: "#ffffff",
  },
  itemsListContainer: {
    backgroundColor: "#ffffff",
    paddingVertical: 8,
    marginHorizontal: 5,
    borderRadius: 10,
  },
  containerScroll: {
    margin: 10,
  },
  imageProductCart: {
    flexDirection: "row",
    width: "50%",
    height: 30,
    top: 0,
    marginBottom: 10,
    marginLeft: 0,
    top: 5,
  },
  imageMethodPay: {
    width: "62%",
    height: 13,
    top: 15,
    marginLeft: 10,
  },
  imageMethodPayCash: {
    width: "60%",
    height: 25,
    top: 15,
    marginLeft: 10,
  },
  imageMethodPayModal: {
    width: "45%",
    height: 12,
    top: 15,
    marginLeft: 0,
  },
  titleProduct: {
    flexDirection: "row",
    marginLeft: -30,
    top: 0,
    fontSize: 10,
    fontWeight: "bold",
  },
  totalPriceProduct: {
    flex: 1,
    fontSize: 18,
    fontWeight: "bold",
    top: 22,
    color: "#FF7F50",
    textAlign: "right",
  },
  totalProduct: {
    flex: 1,
    fontSize: 17,
    fontWeight: "bold",
    color: "#cccccc",
    top: 5,
    textAlign: "right",
    textDecorationLine: "line-through",
    textDecorationStyle: "solid",
  },
  priceProduct: {
    flex: 1,
    fontSize: 10,
    fontWeight: "bold",
    color: "#333333",
    textAlign: "right",
    top: 5,
  },
  quantityProduct: {
    flex: 1,
    fontSize: 11,
    fontWeight: "bold",
    color: "#FF7F50",
    textAlign: "center",
    top: 15,
  },
  containerCart: {
    width: "30%",
    height: 50,
  },
  containerCartPrices: {
    width: "30%",
    height: 80,
  },
  containerTotalLine: {
    width: "100%",
    flexDirection: "row",
    height: 50,
    borderTopWidth: 1,
    top: 20,
    borderTopColor: "#dddddd",
  },
  containerTotal: {
    width: "100%",
    flexDirection: "row",
    height: 35,
    borderTopColor: "#dddddd",
  },
  containerBottomShopping: {
    width: "100%",
    flexDirection: "row",
    height: 60,
    top: 10,
    borderTopColor: "#dddddd",
  },
  containerCartTrash: {
    width: "10%",
    height: 50,
  },
  iconTrash: {
    top: 10,
  },
  titleTotal: {
    fontWeight: "bold",
    fontSize: 22,
    lineHeight: 40,
    color: "#333333",
  },
  subtitle: {
    fontWeight: "bold",
    fontSize: 15,
    lineHeight: 40,
    color: "#333333",
  },
  amount: {
    flex: 1,
    fontSize: 15,
    fontWeight: "bold",
    lineHeight: 40,
    color: "#FF7F50",
    textAlign: "right",
    top: -5,
  },
  totalAmount: {
    flex: 1,
    fontSize: 19,
    fontWeight: "bold",
    lineHeight: 40,
    color: "#FF7F50",
    textAlign: "left",
    top: -5,
  },
  cartTotal: {
    flexDirection: "row",
    borderTopColor: "#dddddd",
    borderTopWidth: 1,
    top: 20,
    flex: 1,
    width: "100%",
    height: 100,
    alignItems: "center",
    justifyContent: "flex-start",
  },

  containerButtonCheckout: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  textTitle: {
    fontSize: 17,
    fontWeight: "bold",
    marginLeft: 15,
    marginTop: 10,
    color: "#FF7F50",
  },
  textTitleMethod: {
    fontSize: 17,
    fontWeight: "bold",
    marginLeft: 0,
    marginTop: 10,
    color: "#FF7F50",
  },
  textTitleMethodPay: {
    fontSize: 17,
    fontWeight: "bold",
    marginLeft: 0,
    marginTop: 10,
    color: "#333333",
  },
  textDirectionMain: {
    fontSize: 15,
    fontWeight: "light",
    marginLeft: 10,
    marginTop: 5,
    color: "#333333",
  },
  textNumberPhone: {
    fontSize: 14,
    fontWeight: "bold",
    top: -15,
    marginLeft: 15,
    color: "#333333",
  },
  iconDirection: { top: 5 },
  iconDirectionMain: {},
  iconNewCard: { marginLeft: 10 },
  iconMethod: { top: 9 },
  containerDirection: {
    flexDirection: "row",
    width: "100%",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    marginBottom: 10,
    marginLeft: 15,
    marginTop: 10,
    height: 50,
  },
  bottomModalView: {
    justifyContent: "flex-end",
    margin: 0,
  },
  button: {
    width: "50%",
    borderRadius: 10,
    borderWidth: 2,
    borderStyle: "solid",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "limegreen",
  },
  buttonText: {
    fontWeight: "bold",
  },
  modal: {
    width: "100%",
    height: "90%",
    borderWidth: 0,
    borderStyle: "solid",
    backgroundColor: "#cccccc",
    marginBottom: -50,
  },
  modalDirection: {
    width: "100%",
    height: "70%",
    borderRadius: 20,
    borderWidth: 0,
    borderStyle: "solid",
    backgroundColor: "#f2f2f2",
  },
  modalMethods: {
    width: "100%",
    height: "90%",
    borderRadius: 20,
    borderWidth: 0,
    borderStyle: "solid",
    backgroundColor: "#f2f2f2",
  },
  modalText: {
    fontSize: 20,
  },
  iconCloseModal: {
    margin: 10,
  },
  bottomMap: {
    flex: 1,
    alignItems: "center",
    borderRadius: 180,
    width: 50,
    height: 50,
    marginLeft: 10,
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
    top: -250,
  },
  map: {
    width: "100%",
    height: 300,
    borderRadius: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  containerMap: {
    width: "100%",
    height: "100%",
    backgroundColor: "#cccccc",
    borderRadius: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    top: -45,
  },
  containerInfoDirection: {
    width: "93%",
    backgroundColor: "#ffffff",
    height: "100%",
    borderRadius: 10,
    marginLeft: 10,
    top: -150,
  },
  input: {
    backgroundColor: "#EEF1F8",
    color: "black",
    width: "45%",
    height: 40,
    marginTop: 10,
    marginLeft: 10,
    paddingLeft: 10,
    borderRadius: 10,
  },
  inputNumber: {
    backgroundColor: "#EEF1F8",
    color: "black",
    width: "93%",
    height: 40,
    marginTop: 10,
    marginLeft: 10,
    paddingLeft: 10,
    borderRadius: 10,
  },
  containerInfoReception: {
    flexDirection: "row",
    width: "100%",
    height: 50,
  },
  containerInfoReceptionSecond: {
    flexDirection: "row",
    width: "100%",
    marginTop: 10,
  },
  containerInfoReceptionThird: {
    flexDirection: "flex-start",
    width: "93%",
    marginTop: 15,
    marginLeft: 10,
    justifyContent: "center",
  },
  titleMain: {
    fontSize: 17,
    fontWeight: "bold",
    marginTop: 10,
    marginLeft: 10,
    marginBottom: 10,
    color: "#FF7F50",
  },
  textDirection: {
    fontSize: 15,
    fontWeight: "lighter",
    marginLeft: 0,
    marginBottom: 10,
    marginTop: 0,
    color: "#333333",
  },
  subtitleMain: {
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 10,
    color: "#FF7F50",
  },
  containerDirections: {
    width: "93%",
    backgroundColor: "#ffffff",
    height: "85%",
    top: 5,
    borderRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 3,
    shadowOpacity: 1.0,
    elevation: 3,
    marginBottom: 10,
    marginLeft: 10,
  },
  containerCards: {
    width: "93%",
    backgroundColor: "#ffffff",
    height: "auto",
    top: 5,
    borderRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 3,
    shadowOpacity: 1.0,
    elevation: 3,
    marginBottom: 10,
    marginLeft: 10,
  },
  lineSeparator: {
    borderBottomWidth: 1,
    borderBottomColor: "#dddddd",
    width: "90%",
    left: 15,
  },
  containerDirectionSecond: {
    marginBottom: 10,
    marginLeft: 15,
    marginTop: 15,
    flex: 1,
    flexDirection: "row",
    width: "90%",
    height: 50,
  },
  nameDirection: {
    fontSize: "16",
    fontWeight: "bold",
    color: "#FF7F50",
  },
  numberCard: {
    fontSize: "16",
    fontWeight: "bold",
    color: "#333333",
    top: 15,
    marginLeft: -10,
  },
  containerCard: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 50,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  titleDirection: {
    fontSize: "13",
    fontWeight: "lighter",
  },
  titleModalDirection: {
    textAlign: "center",
    top: -30,
    fontSize: 18,
    color: "#333333",
    fontWeight: "bold",
  },
  containerTextDirection: {
    width: "90%",
  },
  spinnerTextStyle: {
    color: "#FFFFFF",
  },
});
export default styles;
